from __future__ import annotations

from agent.platforms.models import PlatformCapability, PlatformCapabilityStatus, PlatformKind
from agent.safety.policy import RiskLevel
from agent.safety.trust import TrustLevel


DOCS_MATRIX = "docs/platforms/CAPABILITY_MATRIX.md"
DOCS_STRATEGY = "docs/platforms/PLATFORM_BRIDGE_STRATEGY.md"


def _capability(
    capability_id: str,
    platform: PlatformKind,
    name: str,
    description: str,
    status: PlatformCapabilityStatus,
    risk_level: RiskLevel,
    trust_level: TrustLevel,
    approval_required: bool | str,
    provider: str,
    setup_hint: str,
    *,
    docs_path: str = DOCS_MATRIX,
    command_examples: tuple[str, ...] = (),
    lazy_load_module: str | None = None,
    performance_notes: str = "Static metadata only; does not import platform modules or execute actions.",
) -> PlatformCapability:
    return PlatformCapability(
        capability_id=capability_id,
        platform=platform,
        name=name,
        description=description,
        status=status,
        risk_level=risk_level,
        trust_level=trust_level,
        default_enabled=False,
        approval_required=approval_required,
        provider=provider,
        setup_hint=setup_hint,
        docs_path=docs_path,
        command_examples=command_examples,
        lazy_load_module=lazy_load_module,
        performance_notes=performance_notes,
    )


STATIC_PLATFORM_CAPABILITIES: tuple[PlatformCapability, ...] = (
    _capability(
        "macos.calendar.read",
        PlatformKind.MACOS,
        "macOS calendar read",
        "Future selected-scope calendar reads through a permissioned macOS bridge.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.HIGH,
        TrustLevel.LOCAL_PRIVATE_DATA,
        True,
        "macos_bridge",
        "Planned only. Requires a future manifest entry, selected-scope permission model, ToolBroker mapping, approval gate, and audit coverage.",
        lazy_load_module="agent.platforms.macos.bridge",
    ),
    _capability(
        "macos.calendar.write",
        PlatformKind.MACOS,
        "macOS calendar write",
        "Future approved calendar creates, updates, and deletes.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.CRITICAL,
        TrustLevel.LOCAL_PRIVATE_DATA,
        "per_action",
        "macos_bridge",
        "Planned only. CRITICAL writes require exact preview, per-action approval, no approval reuse, ToolBroker execution, and audit evidence.",
        lazy_load_module="agent.platforms.macos.bridge",
    ),
    _capability(
        "macos.contacts.search",
        PlatformKind.MACOS,
        "macOS contact search",
        "Future selected-scope contact search through a permissioned macOS bridge.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.HIGH,
        TrustLevel.LOCAL_PRIVATE_DATA,
        True,
        "macos_bridge",
        "Planned only. Personal-data reads stay disabled until a selected-scope permission and approval path exists.",
        lazy_load_module="agent.platforms.macos.bridge",
    ),
    _capability(
        "macos.contacts.update",
        PlatformKind.MACOS,
        "macOS contact update",
        "Future approved contact edits.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.CRITICAL,
        TrustLevel.LOCAL_PRIVATE_DATA,
        "per_action",
        "macos_bridge",
        "Planned only. Contact writes require exact per-action approval and no approval reuse before execution.",
        lazy_load_module="agent.platforms.macos.bridge",
    ),
    _capability(
        "macos.file_picker",
        PlatformKind.MACOS,
        "macOS file picker",
        "Future user-selected file or folder handoff.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.MEDIUM,
        TrustLevel.TRUSTED_USER,
        False,
        "macos_bridge",
        "Planned only. Selection must be explicit and future file access must still respect workspace and policy boundaries.",
        lazy_load_module="agent.platforms.macos.bridge",
    ),
    _capability(
        "macos.security_scoped_bookmark",
        PlatformKind.MACOS,
        "macOS security-scoped bookmark",
        "Future persistence of user-granted scoped file access.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.HIGH,
        TrustLevel.LOCAL_PRIVATE_DATA,
        True,
        "macos_bridge",
        "Planned only. Requires explicit user grant, lifecycle docs, revocation behavior, and audit coverage.",
        lazy_load_module="agent.platforms.macos.bridge",
    ),
    _capability(
        "macos.messages.probe",
        PlatformKind.MACOS,
        "macOS Messages probe",
        "Future metadata-only Messages feasibility/status probe.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.MEDIUM,
        TrustLevel.LOCAL_PRIVATE_DATA,
        False,
        "macos_bridge",
        "Planned only. Must not read message content, private Messages databases, or request Full Disk Access.",
        lazy_load_module="agent.platforms.macos.bridge",
    ),
    _capability(
        "macos.notifications",
        PlatformKind.MACOS,
        "macOS notifications",
        "Future local notification display.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.LOW,
        TrustLevel.TRUSTED_USER,
        False,
        "macos_bridge",
        "Planned only. Notification permissions must be explicit and status checks must remain metadata-only.",
        lazy_load_module="agent.platforms.macos.bridge",
    ),
    _capability(
        "ios.message_compose_handoff",
        PlatformKind.IOS_COMPANION,
        "iOS compose handoff",
        "Future user-confirmed mobile compose handoff.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.CRITICAL,
        TrustLevel.UNTRUSTED_MESSAGE,
        "per_action",
        "ios_companion_bridge",
        "Planned only. Handoff must require exact preview, user interaction in native UI, per-action approval, and no silent send.",
        lazy_load_module="agent.platforms.ios_companion.bridge",
    ),
    _capability(
        "ios.mobile_approval",
        PlatformKind.IOS_COMPANION,
        "iOS mobile approval",
        "Future mobile approval review for pending actions.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.HIGH,
        TrustLevel.TRUSTED_USER,
        True,
        "ios_companion_bridge",
        "Planned only. Mobile approval cannot bypass ApprovalManager and CRITICAL actions still require exact per-action approval.",
        lazy_load_module="agent.platforms.ios_companion.bridge",
    ),
    _capability(
        "ios.notification",
        PlatformKind.IOS_COMPANION,
        "iOS companion notification",
        "Future local/mobile companion notification display.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.LOW,
        TrustLevel.TRUSTED_USER,
        False,
        "ios_companion_bridge",
        "Planned only. Notification permission must be explicit and status checks must remain metadata-only.",
        lazy_load_module="agent.platforms.ios_companion.bridge",
    ),
    _capability(
        "ios.quick_action",
        PlatformKind.IOS_COMPANION,
        "iOS companion quick action",
        "Future user-initiated quick action from a companion app.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.MEDIUM,
        TrustLevel.TRUSTED_USER,
        False,
        "ios_companion_bridge",
        "Planned only. Quick actions must be user-initiated and future execution still requires ToolBroker and policy mapping.",
        lazy_load_module="agent.platforms.ios_companion.bridge",
    ),
    _capability(
        "ios.pairing",
        PlatformKind.IOS_COMPANION,
        "iOS companion pairing",
        "Future local pairing flow for a companion app.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.HIGH,
        TrustLevel.LOCAL_PRIVATE_DATA,
        True,
        "ios_companion_bridge",
        "Planned only. Pairing requires explicit user setup, revocation behavior, no remote access by default, and audit coverage.",
        lazy_load_module="agent.platforms.ios_companion.bridge",
    ),
    _capability(
        "windows.platform_doctor",
        PlatformKind.WINDOWS,
        "Windows platform doctor",
        "Future read-only Windows platform status.",
        PlatformCapabilityStatus.STUBBED,
        RiskLevel.SAFE,
        TrustLevel.LOCAL_PRIVATE_DATA,
        False,
        "windows_bridge",
        "Stubbed metadata target only. It must not import Windows UI Automation or read personal data.",
        lazy_load_module="agent.platforms.windows.bridge",
    ),
    _capability(
        "windows.file_picker",
        PlatformKind.WINDOWS,
        "Windows file picker",
        "Future user-selected file or folder handoff.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.MEDIUM,
        TrustLevel.TRUSTED_USER,
        False,
        "windows_bridge",
        "Planned only. Explicit user selection and policy-bounded path handling are required before use.",
        lazy_load_module="agent.platforms.windows.bridge",
    ),
    _capability(
        "windows.notifications",
        PlatformKind.WINDOWS,
        "Windows notifications",
        "Future local notification display.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.LOW,
        TrustLevel.TRUSTED_USER,
        False,
        "windows_bridge",
        "Planned only. Notification permissions must be explicit and status checks must remain metadata-only.",
        lazy_load_module="agent.platforms.windows.bridge",
    ),
    _capability(
        "windows.ui_automation",
        PlatformKind.WINDOWS,
        "Windows UI Automation",
        "Future selected UI Automation workflows.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.CRITICAL,
        TrustLevel.LOCAL_PRIVATE_DATA,
        "per_action",
        "windows_bridge",
        "Planned only. Real UI Automation requires a future decision, manifest entry, exact preview, approval, and audit evidence.",
        lazy_load_module="agent.platforms.windows.bridge",
    ),
    _capability(
        "microsoft_graph.mail",
        PlatformKind.WINDOWS,
        "Microsoft Graph mail",
        "Future selected mail read or send actions via Microsoft Graph.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.CRITICAL,
        TrustLevel.UNTRUSTED_EMAIL,
        "per_action",
        "microsoft_graph",
        "Planned only. OAuth scopes, selected-scope reads, send/write gates, and per-action approvals are required before use.",
        lazy_load_module="agent.platforms.windows.bridge",
    ),
    _capability(
        "microsoft_graph.calendar",
        PlatformKind.WINDOWS,
        "Microsoft Graph calendar",
        "Future selected calendar read/write actions via Microsoft Graph.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.CRITICAL,
        TrustLevel.LOCAL_PRIVATE_DATA,
        "per_action",
        "microsoft_graph",
        "Planned only. Read/write scopes must be separated and CRITICAL writes require exact per-action approval.",
        lazy_load_module="agent.platforms.windows.bridge",
    ),
    _capability(
        "microsoft_graph.contacts",
        PlatformKind.WINDOWS,
        "Microsoft Graph contacts",
        "Future selected contact read/write actions via Microsoft Graph.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.CRITICAL,
        TrustLevel.LOCAL_PRIVATE_DATA,
        "per_action",
        "microsoft_graph",
        "Planned only. Personal-data access remains disabled until selected-scope policy and approval gates exist.",
        lazy_load_module="agent.platforms.windows.bridge",
    ),
    _capability(
        "windows.outlook_bridge",
        PlatformKind.WINDOWS,
        "Windows Outlook bridge",
        "Future selected Outlook mail/calendar bridge.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.CRITICAL,
        TrustLevel.UNTRUSTED_EMAIL,
        "per_action",
        "windows_bridge",
        "Planned only. Outlook reads/writes require selected scopes, manifest entries, exact previews for writes/sends, approvals, and audit evidence.",
        lazy_load_module="agent.platforms.windows.bridge",
    ),
    _capability(
        "windows.teams_bridge",
        PlatformKind.WINDOWS,
        "Windows Teams bridge",
        "Future selected Microsoft Teams messaging/meeting bridge.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.CRITICAL,
        TrustLevel.UNTRUSTED_MESSAGE,
        "per_action",
        "windows_bridge",
        "Planned only. Teams reads/sends require selected scopes, exact per-action approval for sends, and no silent or bulk messaging path.",
        lazy_load_module="agent.platforms.windows.bridge",
    ),
    _capability(
        "app_bridge.status",
        PlatformKind.WEB,
        "App bridge status",
        "Future localhost or IPC frontend status endpoint.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.SAFE,
        TrustLevel.LOCAL_PRIVATE_DATA,
        False,
        "web_app_bridge",
        "Planned only. Status endpoints must stay local/IPC, metadata-only, and disabled unless explicitly configured.",
        docs_path=DOCS_STRATEGY,
        lazy_load_module="agent.platforms.web_bridge.bridge",
    ),
    _capability(
        "app_bridge.pending_actions",
        PlatformKind.WEB,
        "App bridge pending actions",
        "Future redacted pending Action Center metadata for local frontends.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.MEDIUM,
        TrustLevel.LOCAL_PRIVATE_DATA,
        False,
        "web_app_bridge",
        "Planned only. Pending-action views must be redacted and cannot approve or execute actions by themselves.",
        docs_path=DOCS_STRATEGY,
        lazy_load_module="agent.platforms.web_bridge.bridge",
    ),
    _capability(
        "app_bridge.submit_approval",
        PlatformKind.WEB,
        "App bridge submit approval",
        "Future user approval submission surface for a local app frontend.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.HIGH,
        TrustLevel.TRUSTED_USER,
        True,
        "web_app_bridge",
        "Planned only. Frontends cannot bypass ApprovalManager or approve their own generated action without user interaction.",
        docs_path=DOCS_STRATEGY,
        lazy_load_module="agent.platforms.web_bridge.bridge",
    ),
    _capability(
        "app_bridge.audit_summary",
        PlatformKind.WEB,
        "App bridge audit summary",
        "Future redacted audit summary for a local app frontend.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.MEDIUM,
        TrustLevel.LOCAL_PRIVATE_DATA,
        False,
        "web_app_bridge",
        "Planned only. Audit summaries must be redacted and must not expose raw secrets, personal data, or full action bodies.",
        docs_path=DOCS_STRATEGY,
        lazy_load_module="agent.platforms.web_bridge.bridge",
    ),
    _capability(
        "app_bridge.connector_status",
        PlatformKind.WEB,
        "App bridge connector status",
        "Future connector/provider status metadata for a local app frontend.",
        PlatformCapabilityStatus.PLANNED,
        RiskLevel.SAFE,
        TrustLevel.LOCAL_PRIVATE_DATA,
        False,
        "web_app_bridge",
        "Planned only. Connector status must remain metadata-only and must not trigger provider calls or personal-data reads.",
        docs_path=DOCS_STRATEGY,
        lazy_load_module="agent.platforms.web_bridge.bridge",
    ),
)
