from __future__ import annotations

from enum import StrEnum


class TrustLevel(StrEnum):
    TRUSTED_USER = "TRUSTED_USER"
    MODEL_OUTPUT = "MODEL_OUTPUT"
    LOCAL_PRIVATE_DATA = "LOCAL_PRIVATE_DATA"
    UNTRUSTED_WEB = "UNTRUSTED_WEB"
    UNTRUSTED_EMAIL = "UNTRUSTED_EMAIL"
    UNTRUSTED_MESSAGE = "UNTRUSTED_MESSAGE"
    UNTRUSTED_DOCUMENT = "UNTRUSTED_DOCUMENT"
